"""Add unique constraint title+company

Revision ID: 0c3a54c775e4
Revises: 
Create Date: 2025-11-25 16:59:51.504886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3a54c775e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_title_company', ['title', 'company'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint('uq_title_company', type_='unique')

    # ### end Alembic commands ###
